### ISSUE TITLE
Error: There Is No such TimeTable

### ISSUE THREAD

**Issue by Harish795** [teja156/microsoft-teams-class-attender#17]
```
1. Modify Timetable
2. View Timetable
3. Start Bot
Enter option : 2
Traceback (most recent call last):
  File "bot.py", line 267, in <module>
    view_timetable()
  File "bot.py", line 121, in view_timetable
    for row in c.execute('SELECT * FROM timetable'):
sqlite3.OperationalError: no such table: timetable
PS F:\FR\microsoft-teams-class-attender-main (1)\microsoft-teams-class-attender-main> python bot.py
1. Modify Timetable
2. View Timetable
3. Start Bot
Enter option : 1
1. Add class
2. Done adding
Enter option : 1
Enter class name : Hello
Enter class start time in 24 hour format: (HH:MM) 08:15
Enter class end time in 24 hour format: (HH:MM) 10:15
Enter day (Monday/Tuesday/Wednesday..etc) : Tuesday
Traceback (most recent call last):
  File "bot.py", line 265, in <module>
    add_timetable()
  File "bot.py", line 108, in add_timetable
    c.execute("INSERT INTO timetable VALUES ('%s','%s','%s','%s')"%(name,start_time,end_time,day))
sqlite3.OperationalError: no such table: timetable
```

**Comment by Harish795** [comment]
I Was Adding A Timetable and got this
what's the problem

**Comment by Harish795** [comment]
OK I got the problem
