### ISSUE TITLE
doesn't work on repl.it

### ISSUE THREAD

**Issue by PanSmuggler** [teja156/microsoft-teams-class-attender#24]
main.py:207: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
Traceback (most recent call last):
  File "main.py", line 269, in <module>
    sched()
  File "main.py", line 252, in sched
    start_browser()
  File "main.py", line 207, in start_browser
    driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by MatyiFKBT** [comment]
It won't work because selenium needs a chromedriver executable to simulate the browser
