### ISSUE TITLE
I am getting This Error can you please resolve it?

### ISSUE THREAD

**Issue by nagasrisai** [teja156/microsoft-teams-class-attender#31]
bot.py:207: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
Traceback (most recent call last):
  File "C:\Users\babus\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\babus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\babus\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 269, in <module>
    sched()
  File "bot.py", line 252, in sched
    start_browser()
  File "bot.py", line 207, in start_browser
    driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
  File "C:\Users\babus\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\babus\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Shravan-1908** [comment]
duplicate of https://github.com/teja156/microsoft-teams-class-attender/issues/3

**Comment by sandeepDevJs** [comment]
intall chromedriver  from the link below and re run the bot.py

[https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61/](https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61/)
