### ISSUE TITLE
Running into problem when starting bot

### ISSUE THREAD

**Issue by falseprophett** [teja156/microsoft-teams-class-attender#43]
**After starting the bot, the following appears:**

C:\Users\danie\Downloads\microsoft-teams-class-attender-main\microsoft-teams-class-attender-main\bot.py:207: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\danie\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\danie\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\danie\Downloads\microsoft-teams-class-attender-main\microsoft-teams-class-attender-main\bot.py", line 269, in <module>
    sched()
  File "C:\Users\danie\Downloads\microsoft-teams-class-attender-main\microsoft-teams-class-attender-main\bot.py", line 252, in sched
    start_browser()
  File "C:\Users\danie\Downloads\microsoft-teams-class-attender-main\microsoft-teams-class-attender-main\bot.py", line 207, in start_browser
    driver = webdriver.Chrome(chrome_options=opt,service_log_path='NUL')
  File "C:\Users\danie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by kushpareek** [comment]
install chromedriver and then provide path of chrome driver so that it can open the browser

**Comment by jevonmao** [comment]
We should just check chromedriver into version control, and use relative path to find the driver.
