### ISSUE TITLE
sqlite3.OperationalError: no such table: timetable

### ISSUE THREAD

**Issue by ndmparvez** [teja156/microsoft-teams-class-attender#6]
Traceback (most recent call last):
  File "D:\Code\microsoft-teams-class-attender-main\bot.py", line 264, in <module>
    add_timetable()
  File "D:\Code\microsoft-teams-class-attender-main\bot.py", line 107, in add_timetable
    c.execute("INSERT INTO timetable VALUES ('%s','%s','%s','%s')"%(name,start_time,end_time,day))
sqlite3.OperationalError: no such table: timetable

wat shd we do to clear this error

**Comment by Ahsan-x** [comment]
Clone it again and follow steps from Readme

**Comment by saintwithataint** [comment]
I followed all steps from the readme but im still facing the same issue

**Comment by cursedsoulofgods** [comment]
Duplicate of #5

**Comment by Tattesreenu** [comment]
Sme bro mine error

**Comment by coffeeCoder69** [comment]
same error. Does this bot even work?

**Comment by cursedsoulofgods** [comment]
@coffeeCoder69 Before making these assumptions, please see if you have the knowledge of how Python works. Working on fixing this issue.

**Comment by cursedsoulofgods** [comment]
Can you try changing line 108 ``c.execute("INSERT INTO timetable VALUES ('%s','%s','%s','%s')"%(name,start_time,end_time,day))``
to ``c.execute("INSERT INTO timetable.db VALUES ('%s','%s','%s','%s')"%(name,start_time,end_time,day))``
Add a .db infront of the timetable
Also can you please delete the timetable.db and run it again!
If you see an output of "Created Timetable Database" than please tell.
Also attach a screenshot of the error output and the complete output.

**Comment by GreenHckr** [comment]
still not working

**Comment by Tattesreenu** [comment]
Not working

**Comment by sandeepDevJs** [comment]
delete 'timetable.db' and run the bot.py and add new timetable... it will create new timetable.db
